# Etapa de construcción (Build Stage)
FROM golang:1.24.3-alpine AS builder

WORKDIR /app

# Copia los archivos go.mod y go.sum para descargar las dependencias
COPY go.mod ./
COPY go.sum ./

RUN go mod download

# Copia el resto del código fuente de la aplicación
COPY . .

# Compila la aplicación Go.
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api

# Etapa de ejecución (Run Stage)
FROM alpine:latest

EXPOSE 4000

WORKDIR /app

# Copia el binario compilado desde la etapa de construcción
COPY --from=builder /app/main .

# Ejecuta el binario de la aplicación
CMD ["./main"]